module.exports = {
  mySidebar: [
    'index',
    {
      type: 'category',
      label: 'A - D',
      collapsed: true,
      items: [
        'agent-compatibility-with-opcon',
        'aix-system-symitar-upgrade',
        'automate-a-birt-report',
        'automate-ach-file-upload-download-with-axway',
        'automate-ibmi-backup-reorganize-job',
        'avoid-conflicts-between-opcon-and-antivirus',
        'arithmetic-overflow-occurred',
        'basic-troubleshooting-steps',
        'best-practice-for-naming-opcon-objects',
        'cannot-retrieve-a-job-log',
        'change-machine-status-with-an-event',
        'clean-up-opcon-reports-directory',
        'connector-sub-type-not-found-in-enterprise-manager',
        'create-a-complex-frequency',
        'critical-fix-for-unix-lsam-ssh-key-vulnerability',
        'deploy-installation-upgrade',
        'deploy-transformation-rule-unix-start-image'
      ],
    },
    {
      type: 'category',
      label: 'D - H',
      collapsed: true,
      items: [
        'enterprise-manager-report-takes-too-much-time-to-load',
        'event-associated-to-a-user',
        'exit-description-event-trigger-not-working',
        'export-an-enterprise-manager-profile',
        'external-event-password',
        'file-arrival-best-practices',
        'file-arrival-not-detecting-the-file',
        'hide-or-disable-a-self-service-button',
        'history-management-timeout',
        'how-to-install-mslsam-on-a-cluster',
        'how-to-perform-a-restart-point-in-a-symitar-job',
        'how-to-set-specific-permissions-on-a-received-file',
      ],
    },
    {
      type: 'category',
      label: 'I - K',
      collapsed: true,
      items: [
        'ibmi-job-basic-troubleshooting',
        'ibmi-job-messages',
        'ibmi-maintenance',
        'install-enterprise-manager-on-mac',
        'integration-error-after-upgrade-of-aix-on-a-symitar-host',
        'issues-with-automation-of-office-products',
        'java-agent-service-will-not-start',
        'job-dependency-and-auto-restart',
      ],
    },
    {
      type: 'category',
      label: 'L - N',
      collapsed: true,
      items: [
        'license-file-location-and-notifications',
        'locked-resource-in-opcon-that-cannot-be-freed',
        'lsam-not-communicating',
        'lsam-tracking-files-issue',
        'manage-file-arrival-reaching-end-time-with-exit-code-1',
        'manage-the-maximum-number-of-jobs-a-machine-can-run',
        'notifications-delayed',
      ],
    },
    {
      type: 'category',
      label: 'O - R',
      collapsed: true,
      items: [
        'opcon-docker',
        'opcon-job-history-management',
        'opcon-phone-calls',
        'opcon-rest-api-java-client',
        'opcon-services-and-processes',
        'opcon-task-usage-utility-faqs',
        'opcon-task-usage-utility-installation-and-configuration',
        'opcon-web-installer',
        'ports-used-by-opcon-communications',
        'restart-opcon-lsam-server',
        'running-em-from-a-non-standard-location',      ],
    },
    {
      type: 'category',
      label: 'S -T',
      collapsed: true,
      items: [
        'set-opcon-api-certificate',
        'set-up-secure-tls-communication-with-unix-lsam',
        'set-up-secure-tls-communication-with-windows-agent',
        'smart-email-oauth-information',
        'solution-manager-authentication-required',
        'solution-manager-troubleshooting-and-information-gathering',
        'steps-for-updating-smart-email-to-support-ms-oauth',
        'track-unique-tasks-on-your-production',
        'transaction-log-full',
        'troubleshooting-common-windows-job-issues',
        'troubleshooting-opcon-files-locked',
      ],
    },
    {
      type: 'category',
      label: 'U -Z',
      collapsed: true,
      items: [
        'unix-error-this-lsam-version-does-not-support-encrypted-token',
        'unix-lsam-choosing-the-right-tar-file-to-install',
        'unix-lsam-upgrade',
        'use-named-schedule-instances',
        'windows-job-failed-with-encrypted-global-property',
        'winscp-job-configuration',
        'ws-ftp-job-failure-troubleshooting',
      ],
    },
  ],
};
